rad.includes.modules([
    "object",
    "math",
    "vector",
    "mouse",
    "ui",
    "graph"
]);
rad.includes.source([
    "main.js",
    "core/util.js",
    "aed/main.js",
    "aed/graph_symbols.js",
    "aed/graph_colors.js",
    "aed/graph_colors_custom.js",
    "aed/graph_canvas.js",
    "aed/aed.js"
]);
