rad.includes.modules([
    "object",
    "array",
    "math",
    "vector",
    "color",
    "dom",
    "mouse",
    "element",
    "ui",
    "graph",
    "panels",
    "localstorage",
    "io"
]);
rad.includes.source([
    "main.js",
    "core/util.js",
    "aed/main.js",
    "aed/menu_bar.js",
    "aed/graph_ascii.js",
    "aed/graph_symbols.js",
    "aed/graph_symbols_custom.js",
    "aed/graph_colors.js",
    "aed/graph_colors_custom.js",
    "aed/graph_canvas.js",
    "aed/aed.js"
]);
