rad.includes.modules([
    "object",
    "array",
    "math",
    "vector",
    "dom",
    "mouse",
    "element",
    "ui",
    "graph",
    "panels"
]);
rad.includes.source([
    "main.js",
    "core/util.js",
    "aed/main.js",
    "aed/graph_symbols.js",
    "aed/graph_colors.js",
    "aed/graph_colors_custom.js",
    "aed/graph_canvas.js",
    "aed/aed.js"
]);
